dev: true
prod: false
prep: false
docker_host: YPGRW04XAAA000F
sql_svc_acct: svc.ypgr.sediment
rhss_register: "'https://rhss.yuma.army.mil/register?activation_keys=rhel8-ican-lab&lifecycle_environment_id=1&location_id=2&operatingsystem_id=1&organization_id=1&update_packages=false'"
rhss_auth: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJpYXQiOjE3MDczMzkzNTcsImp0aSI6IjlkODkzYTU2NGYyOWI3NzQ5MGNiZTMwMzJkYTU2M2ZjNjhiOWEzNWU4NWE1NzgzNzNjYzEzYmU5ZDg3YmEzMmUiLCJzY29wZSI6InJlZ2lzdHJhdGlvbiNnbG9iYWwgcmVnaXN0cmF0aW9uI2hvc3QifQ.YXToF-ou6jBwDXbBHZKta3_8cvMVgzDDVD-Z-CqYpZk"

# Container Application Backups
volume_backups: 1

# VMWare
vcenter_hostname: "vcs.yuma.army.mil"
vcenter_username: "api@vsphere.local"
vcenter_datacenter: "UCS-Lab"
vcenter_validate_certs: false
vm_folder: "_ServerBuild"
vm_guestid: "ubuntu64Guest"
vm_disk_gb: 80
vm_disk_type: "thick"
vm_state: "powered-on"
vm_disk_datastore: "VMware-Lab2"
vm_hw_ram_mb: 8192
vm_hw_cpu_n: 4
vm_hw_scsi: "paravirtual"
vm_net_name: "VLAN630_LinuxDeployment"
vm_net_type: "vmxnet3"
vm_template: "template_ubuntu-24.04"

# UFW
block_gannon: true
ufw_env:
  - order: 100
    rule: 'deny'
    direction: 'in'
    from_ip: 6.2.2.0/26
    proto: 'any'
    description: "Block external scanners"
  - order: 200
    rule: 'allow'
    direction: 'in'
    from_ip: 6.2.9.184
    proto: 'any'
    description: "Allow 3TN"
  - order: 300
    rule: 'allow'
    direction: 'in'
    from_ip: 6.2.4.38
    proto: 'tcp'
    to_port: 22
    description: "Allow SSH from Shared Dev"
  - order: 400
    rule: 'allow'
    direction: 'in'
    from_ip: 6.2.9.173
    proto: 'tcp'
    to_port: 22
    description: "Allow SSH from thall-Ansible"