# Site
prod: true
prep: false
docker_host: YPGRW04XAAA03AG
sql_svc_acct: "AutomationWorker"
inventory_path: "/var/lib/docker/volumes/semaphore-inv/_data/"
inventory_owner: "1001"
inventory_group: "1001"
rhss_register: "'https://rhss.yuma.army.mil/register?activation_keys=rhel8-ican-prod&lifecycle_environment_id=1&organization_id=1&update_packages=false'"
rhss_auth: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJpYXQiOjE3MDczMzkzNTcsImp0aSI6IjlkODkzYTU2NGYyOWI3NzQ5MGNiZTMwMzJkYTU2M2ZjNjhiOWEzNWU4NWE1NzgzNzNjYzEzYmU5ZDg3YmEzMmUiLCJzY29wZSI6InJlZ2lzdHJhdGlvbiNnbG9iYWwgcmVnaXN0cmF0aW9uI2hvc3QifQ.YXToF-ou6jBwDXbBHZKta3_8cvMVgzDDVD-Z-CqYpZk"

# VMWare
vcenter_hostname: "vcs.yuma.army.mil"
vcenter_username: "api@vsphere.local"
vcenter_datacenter: "UCS-Prod"
vcenter_validate_certs: false
vm_folder: "NEC-ISMO"
vm_guestid: "ubuntu64Guest"
vm_disk_gb: 80
vm_disk_type: "thick"
vm_state: "powered-on"
vm_disk_datastore: "VMware-Prod-3"
vm_hw_ram_mb: 8192
vm_hw_cpu_n: 4
vm_hw_scsi: "paravirtual"
vm_net_name: "VLAN630_LinuxDeployment"
vm_net_type: "vmxnet3"
vm_template: "template_ubuntu-24.04"