trigger: none

pool:
  name: 's6_triggered_24.04'

variables:
  - group: Ansible

steps:
- bash: echo "##vso[task.setvariable variable=vm_name]ansible_$(uuidgen)"
  displayName: Generating hostname

- script: echo $(vm_name)
  displayName: Displaying hostname

- script: pipx upgrade --include-injected ansible
  displayName: 'Upgrade pipx'

- script: rm -f ~/.ssh/known_hosts
  displayName: 'Purging known hosts'

- task: DownloadSecureFile@1
  name: vault_key
  displayName: 'Download SSH Key'
  inputs:
    secureFile: 'vault_key_dev'

- script: >
    ansible-playbook dynamic-site.yml 
    -e 
    "ENV=dev
    HOSTS='nginx'
    validation_group='nginx_validation'
    vm_name=$(Agent.Name)
    rm_hosts_file=/home/ado_build_agent/.ssh/known_hosts
    role=nginx 
    mode=deploy 
    verify_hostname=''
    build_agent_name=$(Agent.Name)" 
    --vault-password-file=$(vault_key.secureFilePath)
  displayName: 'Validating nginx deploy'

- script: >
    ansible-playbook dynamic-site.yml 
    -e
    "run_ubuntu=''
    run_docker=''
    ENV=dev
    vm_name=$(Agent.Name)
    role=nginx 
    mode=bounce 
    verify_hostname=''
    build_agent_name=$(Agent.Name)
    ssh_key=''" 
    --vault-password-file=$(vault_key.secureFilePath)
  displayName: 'Validating nginx bounce'

- script: >
    ansible-playbook dynamic-site.yml 
    -e
    "run_ubuntu=''
    run_docker=''
    ENV=dev
    vm_name=$(Agent.Name)
    role=nginx 
    mode=update 
    verify_hostname=''
    build_agent_name=$(Agent.Name)"    
    --vault-password-file=$(vault_key.secureFilePath)
  displayName: 'Validating nginx update'