trigger: none

pool:
  name: 's6_triggered_24.04'

variables:
  - group: Ansible

steps:
- script: pipx upgrade --include-injected ansible
  displayName: 'Upgrade pipx'

- script: rm -f ~/.ssh/known_hosts
  displayName: 'Purging known hosts'

- task: DownloadSecureFile@1
  name: vault_key
  displayName: 'Download SSH Key'
  inputs:
    secureFile: 'vault_key_dev'

- script: >
    ansible-playbook dynamic-site.yml 
    -e
    "ENV=dev
    role=docker_host
    rm_hosts_file=/home/ado_build_agent/.ssh/known_hosts 
    verify_hostname='' 
    validation_group='docker_validation'
    build_agent_name=$(Agent.Name)
    vm_cleanup=true"
    --vault-password-file=$(vault_key.secureFilePath)
  displayName: 'Validating Docker Role Pass 1'