trigger: none

pool:
  name: 's6_triggered_24.04'

variables:
  - group: Ansible

steps:
- script: pipx upgrade --include-injected ansible
  displayName: 'Upgrade pipx'

- script: rm -f ~/.ssh/known_hosts
  displayName: 'Purging known hosts'

- task: DownloadSecureFile@1
  name: vault_key_dev
  displayName: 'Download SSH Key'
  inputs:
    secureFile: 'vault_key_dev'

- script: >
    ansible-playbook dynamic-site.yml 
    -e 
    "validation_group=fortify_ssc_validation 
    ENV=dev 
    role=fortify_ssc
    rm_hosts_file=/home/ado_build_agent/.ssh/known_hosts 
    verify_hostname=''
    build_agent_name=$(Agent.Name)
    vm_cleanup=true" 
    --vault-password-file=$(vault_key_dev.secureFilePath)
  displayName: 'Validating Fortify role'