trigger: none

pool:
  name: 'nec_ondemand_L'

variables:
  - group: Ansible

  - group: YPG_Environment

steps:
- script: python3 -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: python3 -m pip install --upgrade ansible
  displayName: 'Install ansible'

- task: DownloadSecureFile@1
  name: ssh_key
  displayName: 'Download SSH Key'
  inputs:
    secureFile: 'ypgansible_ssh'

- task: DownloadSecureFile@1
  name: vault_key
  displayName: 'Download SSH Key'
  inputs:
    secureFile: vault_key_prep

- script: chmod 600 $(ssh_key.secureFilePath)
  displayName: 'Setting SSH Key permisisons'

- script: >
    ansible-playbook site.yml
    -i $(inventory_path)/Pre-Production-inventory.yml
    -e
    "HOSTS=YPGRW04XAAA0GPN
    role=keystone
    ENV=prep
    mode=renew
    fast=true"
    --vault-password-file=$(vault_key.secureFilePath)
    --key-file '$(ssh_key.secureFilePath)'
  displayName: 'Renewing Keystone TGT'